import os
import aiohttp
import logging
from typing import Optional, Dict, Any

logger = logging.getLogger("InfiniteCore.Ollama")

class OllamaAI:
    def __init__(self):
        self.host = os.getenv("OLLAMA_HOST", "http://127.0.0.1:11434")
        self.model = os.getenv("OLLAMA_MODEL", "qwen3:8b")
        self.enabled = os.getenv("AI_ENABLED", "true").lower() == "true"

    async def generate_response(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        if not self.enabled:
            return "AI module is currently disabled by administrator."

        url = f"{self.host}/api/generate"
        default_system = (
            "You are Infinite Core AI, an expert customer assistant for a high-performance hosting provider. "
            "You help users with VPS hosting, Minecraft servers, plan selection, and troubleshooting. "
            "Be concise, polite, professional, and clear. Do not issue administrative actions directly."
        )
        payload = {
            "model": self.model,
            "prompt": prompt,
            "system": system_prompt or default_system,
            "stream": False
        }

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(url, json=payload, timeout=aiohttp.ClientTimeout(total=30)) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        return data.get("response", "No response generated by AI.")
                    else:
                        logger.error(f"Ollama error status: {resp.status}")
                        return "Local AI server returned an error."
        except Exception as e:
            logger.error(f"Failed to connect to Ollama at {self.host}: {e}")
            return "Local AI service (Ollama) is offline or unreachable."

    async def detect_intent(self, text: str) -> Dict[str, Any]:
        prompt = (
            f"Analyze the intent of the following user message: '{text}'\n"
            "Respond ONLY with a JSON object containing keys: 'intent' (e.g., 'ban', 'kick', 'buy_vps', 'buy_mc', 'help', 'general'), "
            "'target' (user or plan mentioned), and 'confidence' (0.0 to 1.0)."
        )
        res = await self.generate_response(prompt, system_prompt="You are a strict JSON intent classifier.")
        return {"raw_ai_analysis": res}
      
